---
inputs:
  release:
    default: 13.2-RELEASE
    description: FreeBSD release
    options:
      - 12.2-RELEASE
      - 12.3-RELEASE
      - 12.4-RELEASE
      - 13.0-RELEASE
      - 13.1-RELEASE
      - 13.2-RELEASE
    type: choice

runs:
  using: composite
  steps:
    - name: Package `vagrant box file`
      run: |
        if [ ! -f /tmp/FreeBSD-${{ inputs.release }}.box ]; then
          vagrant ssh --command "find ${{ github.workspace }} -mindepth 1 -delete"
          vagrant ssh --command "find ${{ runner.temp }} -mindepth 1 -delete"
          vagrant ssh --command "sudo pkg clean --all --yes"
          vagrant package --output /tmp/FreeBSD-${{ inputs.release }}.box
        fi
      shell: /bin/bash {0}
