---
name: Stop & package Vagrant Box

inputs:
  pre-package-commands:
    default: >-
      find ${{ github.workspace }} -mindepth 1 -delete;
      find ${{ runner.temp }} -mindepth 1 -delete;
      sudo pkg clean --all --yes;
    description: Command(s) to run before packaging
    type: string

runs:
  using: composite
  steps:
    - name: Package `vagrant box`
      run: |
        if [ ! -f /tmp/packaged.box ]; then
          vagrant ssh --command "${{ inputs.pre-package-commands }}"
          vagrant package --output /tmp/packaged.box
        fi
      shell: /bin/bash --noprofile --norc -euxo pipefail {0}
